<?php

namespace Checkengine\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BusquedaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusquedaRepository extends EntityRepository
{
    public function queryFindBusquedaUsuario($busca,$usuario) {
        $query= $this->getEntityManager()->createQueryBuilder();
            $query->select('e')
                ->from('Checkengine\DashboardBundle\Entity\Busqueda', 'e')
                ->orderBy('e.createdAt', 'DESC'); 
            $query->andWhere('e.slug LIKE :tipo')
                  ->setParameter('tipo', "%".$busca."%");
            $query->leftJoin('e.usuario', 'u');
            $query->andWhere('u.id=:usuario')
                  ->setParameter('usuario', $usuario);
        return $query->getQuery();

    }

    public function findBusquedaUsuario($busca,$usuario) {
        return $this->queryFindBusquedaUsuario($busca,$usuario)->getOneOrNullResult();
    }
}
