<?php

namespace Checkengine\DashboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactoRepository extends EntityRepository
{
    public function queryFindContactosAdmin($buscar = "") {
        $em = $this->getEntityManager();
        if (strlen($buscar) == 0) {
            $consulta = $em->createQuery('SELECT u '
                    . 'FROM DashboardBundle:Contacto u '
                    . 'ORDER BY u.updateAt DESC');
        } else {
            $consulta = $em->createQuery("SELECT c "
                    . "FROM DashboardBundle:Empresa c "
                    . "JOIN c.usuario u "
                    . "WHERE u.nombre LIKE :nombre OR u.apellido LIKE :apellido OR u.email LIKE :email "
                    . "ORDER BY c.updateAt DESC");
            $consulta->setParameters(array(
                'nombre' => "%" . $buscar . "%",
                'apellido' => "%" . $buscar . "%",
                'email' => "%" . $buscar . "%"
            ));
        }
        return $consulta;
    }

    public function findContactosAdmin($buscar = "") {
        return $this->queryFindContactosAdmin($buscar)->getResult();
    }
    
    public function queryFindContactosCliente($usuario) {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('SELECT u '
            . 'FROM DashboardBundle:Contacto u '
            . "JOIN c.usuario u "
            . "WHERE u.id=:usuario "
            . 'ORDER BY u.updateAt DESC');
        $consulta->setParameters(array(
            'usuario'=>$usuario,
        ));
        return $consulta;
    }

    public function findContactosCliente($usuario) {
        return $this->queryFindContactosCliente($usuario)->getResult();
    }
}
