<?php

namespace Checkengine\DashboardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EspecialidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspecialidadRepository extends EntityRepository
{
    public function queryFindByTipoDeEmpresa($tipo = "") {
        $em = $this->getEntityManager();
        if (strlen($tipo) == 0) {
            $consulta = $em->createQuery('SELECT u '
                    . 'FROM DashboardBundle:Especialidad u '
                    . 'ORDER BY u.tipoEmpresa ASC, u.orden ASC');
        } else {
            $consulta = $em->createQuery("SELECT u "
                    . "FROM DashboardBundle:Vehiculo u "
                    . "WHERE u.tipoEmpresa=:tipo "
                    . "ORDER BY u.tipoEmpresa ASC, u.orden ASC");
            $consulta->setParameters(array(
                'tipoEmpresa' =>  $tipo
            ));
        }
        return $consulta;
    }

    public function findByTipoDeEmpresa($tipo = "") {
        return $this->queryFindByTipoDeEmpresa($tipo)->getResult();
    }
}
