<?php

namespace Checkengine\DashboardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OfertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfertaRepository extends EntityRepository
{
    public function queryFindOfertas($buscar = "") {
        $em = $this->getEntityManager();
        if (strlen($buscar) == 0) {
            $consulta = $em->createQuery('SELECT u '
                    . 'FROM DashboardBundle:Oferta u '
                    . 'ORDER BY u.createdAt DESC');
        } else {
            $consulta = $em->createQuery("SELECT u "
                    . "FROM DashboardBundle:Oferta u "
                    . "JOIN u.usuario e"
                    . "WHERE e.nombre LIKE :nombre OR e.apellidos LIKE :apellidos OR e.email LIKE :email "
                    . "ORDER BY u.createdAt DESC");
            $consulta->setParameters(array(
                'nombre' => "%" . $buscar . "%",
                'apellidos' => "%" . $buscar . "%",
                'email' =>  "%" . $buscar . "%"
            ));
        }
        return $consulta;
    }

    public function findOfertas($buscar = "") {
        return $this->queryFindOfertas($buscar)->getResult();
    }
}
