<?php

namespace Checkengine\DashboardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicioRepository extends EntityRepository
{
    public function queryFindServicios($buscar = "") {
        $em = $this->getEntityManager();
        if (strlen($buscar) == 0) {
            $consulta = $em->createQuery('SELECT u '
                    . 'FROM DashboardBundle:Servicio u '
                    . 'ORDER BY u.nombre ASC');
        } else {
            $consulta = $em->createQuery("SELECT u "
                    . "FROM DashboardBundle:Servicio u "
                    . "WHERE u.nombre LIKE :servicio  "
                    . "ORDER BY u.nombre ASC");
            $consulta->setParameters(array(
                'servicio' => "%" . $buscar . "%"
            ));
        }
        return $consulta;
    }

    public function findServicios($buscar = "") {
        return $this->queryFindServicios($buscar)->getResult();
    }
}
