<?php

namespace Checkengine\DashboardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository {

    public function queryFindUsuarios($buscar = "") {
        $em = $this->getEntityManager();
        if (strlen($buscar) == 0) {
            $consulta = $em->createQuery('SELECT u '
                    . 'FROM DashboardBundle:Usuario u '
                    . 'ORDER BY u.nombre ASC, u.apellidos ASC');
        } else {
            $consulta = $em->createQuery("SELECT u "
                    . "FROM DashboardBundle:Usuario u "
                    . "WHERE u.nombre LIKE :nombre OR u.apellidos LIKE :apellidos OR u.email LIKE :email "
                    . "ORDER BY u.nombre ASC, u.apellidos ASC");
            $consulta->setParameters(array(
                'nombre' => "%" . $buscar . "%",
                'apellidos' => "%" . $buscar . "%",
                'email' => "%" . $buscar . "%"
            ));
        }
        return $consulta;
    }

    public function findUsuarios($buscar = "") {
        return $this->queryFindUsuarios($buscar)->getResult();
    }

}
