<?php

namespace Checkengine\DashboardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VehiculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculoRepository extends EntityRepository
{
    public function queryFindVehiculos($buscar = "") {
        $em = $this->getEntityManager();
        if (strlen($buscar) == 0) {
            $consulta = $em->createQuery('SELECT u '
                    . 'FROM DashboardBundle:Vehiculo u '
                    . 'ORDER BY u.marca ASC, u.modelo ASC, u.year ASC');
        } else {
            $consulta = $em->createQuery("SELECT u "
                    . "FROM DashboardBundle:Vehiculo u "
                    . "WHERE u.marca LIKE :marca OR u.modelo LIKE :modelo OR u.year=:year "
                    . "ORDER BY u.marca ASC, u.modelo ASC, u.year ASC");
            $consulta->setParameters(array(
                'marca' => "%" . $buscar . "%",
                'modelo' => "%" . $buscar . "%",
                'year' =>  $buscar
            ));
        }
        return $consulta;
    }

    public function findVehiculos($buscar = "") {
        return $this->queryFindVehiculos($buscar)->getResult();
    }
}
